<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AudioFiles\best-adventure-ever-122726.mp3" />
    <None Remove="Assets\AudioFiles\cinematic-slow-sad-piano-soundtrack-187684.mp3" />
    <None Remove="Assets\AudioFiles\Happy.mp3" />
    <None Remove="Assets\AudioFiles\Somber.mp3" />
    <None Remove="Assets\AudioFiles\Tense.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\AudioFiles\Happy.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\AudioFiles\Somber.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\AudioFiles\Tense.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
